django1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

import users.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("django1app.urls")),
    path('users/', include('users.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page="django1app:index"), name = 'logout'),

]

django1app/urls.py
"""Defines the url patterns for django1app"""

from django.urls import path
from . import views

app_name = "django1app"
urlpatterns=[
    #home page
    path("",views.index,name="index"),

    #show all topics
    path("topics/", views.topics,name="topics"),
    #detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #Page for adding new Topics
    path('new_topic/', views.new_topic, name='new_topic'),
    #page for adding new Entries
    path('new_entry/<int:topic_id>/', views.new_entry,name ='new_entry' ),
    #page for editing entries
    path('edit_entry/<int:entry_id>/', views.edit_entry, name ='edit_entry'),



]

mealplanner/mealplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mymealplanner.urls")),
]

mealplanner/mymealplanner/urls.py
"""degine url patterns for my mealplanner app"""

from django.urls import path
from . import views

app_name = "mymealplanner"
urlpatterns =[
    path("",views.index, name="index"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView

from . import views

app_name = 'users'

urlpatterns = [
    # login page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    #registration page
    path('register', views.register, name='register'),

]

django1app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about"""
    text=models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Retrun self string representation of the model"""
        return self.text

class Entry(models.Model):
    """Somethinh specific about topics"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text)<51:
            return self.text
        else:
            return f"{self.text[:50]}..."

mealplanner/mymealplanner/models.py
from django.db import models

# Create your models here.
class MPStrategy(models.Model):
    """able to define different mealplans"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string reprensation of the model"""
        return self.text

class MPDetails(models.Model):
    """add information to the strategy"""
    text = models.CharField(max_length=200)
    date_added= models.DateTimeField(auto_now_add=True)
    strategy= models.ForeignKey(MPStrategy,on_delete=models.CASCADE)


    def __str__(self):
        """return text"""
        return self.text

users/models.py
from django.db import models

# Create your models here.

django1app/forms.py
from django import forms
from .models import Topic,Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels ={'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields= ['text']
        labels= {'text': ''}
        widgets= {'text': forms.Textarea(attrs={'cols': 80})}

django1app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

# Create your views here.
def index(request):
    """The home page for django1app"""
    return render(request,"django1app/index.html")
@login_required()
def topics(request):
    """Show all topics. wehn a user is logged in request contains request.user"""
    topics= Topic.objects.filter(owner=request.user).order_by('date_added')
    context={"topics":topics}
    return render(request, "django1app/topics.html", context)

@login_required()
def topic(request, topic_id):
    """shows a single topic all its entries"""
    topic= Topic.objects.get(id=topic_id)

    """check if users == author"""
    if request.user != topic.owner:
        raise Http404
    entries= topic.entry_set.order_by("-date_added")
    """the - reverses the order, so most recent first"""
    context = {"topic" : topic, "entries" : entries}
    return render(request, "django1app/topic.html", context)

@login_required()
def new_topic(request):
    """add a new topic"""
    if request.method != 'POST':
        #No data submitted; create a blank form
        form = TopicForm()
    else:
        #Post data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic=form.save(commit=False)
            new_topic.owner= request.user
            form.save()
            return HttpResponseRedirect(reverse('django1app:topics'))

    context = {'form': form}
    return render(request, 'django1app/new_topic.html', context)

@login_required()
def new_entry(request,topic_id):
    """add a new entry linked to a topic"""
    topic = Topic.objects.get(id=topic_id)
    if not check_if_owner_topicid(request,topic_id):
        raise Http404
    if request.method != 'POST':
        #no data was entered,create blank+
        form=EntryForm()

    else:
        #post data submitted, process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('django1app:topic',args=[topic_id]))

    context={'topic':topic,'form':form}
    return render(request, 'django1app/new_entry.html', context)

@login_required()
def edit_entry(request,entry_id):
    """edit an existing entry"""
    entry= Entry.objects.get(id=entry_id)
    topic = entry.topic

    if not check_if_owner_topicid(request,topic.id):
        raise Http404

    if request.method != 'POST':
        #get the current entry to then be able to edit it
        form= EntryForm(instance=entry)

    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('django1app:topic', args=[topic.id]))

    context ={'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'django1app/edit_entry.html', context)

def check_if_owner_topicid(request,topic_id):
    topic=Topic.objects.get(id=topic_id)
    if request.user == topic.owner:
        return True
    else:
        return False

mealplanner/mymealplanner/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    """the homepage for my mealplanner"""
    return render(request,"mymealplanner/index.html")

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate,login
from  django.http import HttpResponseRedirect
from django.contrib.auth.forms import  UserCreationForm


# Create your views here.
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        #display blank reg page
        form = UserCreationForm()
        print("after blankform")

    else:
        #process completed form
        form= UserCreationForm(data=request.POST)
        print("before is valid")

        if form.is_valid():
            print("after is valid")
            new_user = form.save()
            #log the user in and redirect to homepage
            authenticated_user=authenticate(username=new_user.username,password =request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('django1app:index'))

    context={'form': form}
    return render(request, 'users/register.html', context)

django1app/templates/django1app/base.html
<p>
    <a href = '{%url "django1app:index" %}'>Django1App</a> -
    <a href = '{%url "django1app:topics" %}'>Topics</a>-
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Log Out</a>
    {%else %}
    <a href ="{%url 'users:register' %}">register</a>-
    <a href = "{%url 'users:login' %}">log in</a>
    {%endif %}
    {% if request.path != LOGIN_URL and not request.user.is_authenticated %}
        <p>Login required to access this page.</p>
    {% endif %}
       <!-- “Hypertext REFerence"-->

</p>

{%block content %}{% endblock content%}

django1app/templates/django1app/edit_entry.html
{% extends 'django1app/base.html' %}

{%block content %}

<p><a href="{% url 'django1app:topic' topic.id %}">{{topic}}</a> </p>

<p> Edit entry:</p>

<form action="{% url 'django1app:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{form.as_p }}
    <button name="submit">save changes</button>
    </form>

{% endblock content %}

django1app/templates/django1app/forms.html
<p>every form requires an action attribute,requires an url where to submit the form info to,method either get or
    post</p>
<p> input can be combined with type,name,size,maxlength</p>
<ul>
    <p>Input types:</p>
    <li>password(name,size,maxlength)</li>
    <li>testarea(name,cols,rows)</li>
    <li>radio(name,value,checked=checked(preselection)</li>
    <li>checkbox,(name,value(specify what to send),checked</li>
    <li>select(name) then similar to li use option(value,selected) to specify options</li>
    <li>select(name,size,multiple) and then option for multiple options</li>
    <li>file(name)</li>
    <li>submit(name,value)</li>
    <li>image,works as submit but with image</li>
    <li>button(allows to combine text and images"img src| plus button input type hidden(name,value)</li>


</ul>

django1app/templates/django1app/index.html
{%extends "django1app/base.html"%}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>

{% endif %}
{% endblock %}

django1app/templates/django1app/listtest.html
<p> <dfn>ol is an ordered list</dfn></p>
<ol id="ol">
    <li>First add butter and sugar</li>
    <li> then add eggs and flour</li>
    <li> mix and then in the oven</li>
</ol>
<p></p>
<p><dfn>ul is an unordered list</dfn></p>
<ul id="ul">
    <li> his name is peter</li>
    <li> killer whales are dolphins</li>
    <li> i sit next to phranz</li>
</ul>
<p> <dfn> dl are definitions list,dt contains the definition term, dd the definition</dfn></p>
<dl  id="dl">
    <dt>Origami:</dt>
    <dd>
        Origami is the traditional Japanese art of paper folding, creating intricate shapes and designs by folding a single sheet of paper without cutting or gluing. It combines precision and creativity to produce beautiful three-dimensional figures and holds cultural significance in Japanese heritage.
    </dd>
    <dd>
        <br />
    <dl>
        <dt>Nested list</dt>
        <dd>
            In HTML, a nested list refers to a list structure where one list (the inner list) is contained within another list (the outer list). This allows you to create hierarchical or indented lists, commonly used for creating sub-categories or related items within a main list, where each nested list item is further indented to visually represent the hierarchy.
        </dd>
    </dl>
    </dd>
</dl>
<p> to open a link in a new tab use target="_blank"<a href="https://www.google.com" target="_blank">google in a new tab</a> </p>
<ul>
    <li><a href="#ul">ul</a></li>
    <li><a href="#dl">dl</a></li>
    <li><a href="#ol">ol</a></li>
</ul>
<p>we use figure and figcapation to mark a connection,we will ad an image(img src="" alt="descr", title="",width="",height="")</p>
<figure>
<img src="https://deih43ym53wif.cloudfront.net/large_sunset-beach-port-waikato-new-zealand-shutterstock_123331423.jpg_8f4b4080c6.jpg"
     alt="a sunset" title="the sunset"/>
    <figcaption>a sunset</figcaption>
</figure>

django1app/templates/django1app/new_entry.html
{% extends "django1app/base.html" %}

{% block content  %}

<p><a href ="{%url 'django1app:topic' topic.id %}">{{topic }}</a></p>

<p>add a new entry:</p>
<form action ="{%url 'django1app:new_entry' topic.id %}" method="post">
    {%csrf_token %}
    {{form.as_p}}
    <button name=" submit"> add entry</button>
</form>

{% endblock content %}

django1app/templates/django1app/new_topic.html
{% extends "django1app/base.html" %}

{%block content%}
    <p> Add a new topic</p>
    <form action = "{%url 'django1app:new_topic' %}" method="post">
        {%csrf_token %}
        {{form.as_p}}
        <buttom name="submit">add topic</buttom>
    </form>
{% endblock content %}

django1app/templates/django1app/tablestest.html
<table>
    <tr>
        <th></th>
        <th scope="col">col1</th>
        <th scope="col">col2</th>
    </tr>
    <tr>
        <th scope="row">data 1</th>
        <td>data 11</td>
        <td>data 12</td>
    </tr>
    <tr>
        <th scope="row">data2</th>
        <td>data 21</td>
        <td>data 22</td>
    </tr>

</table>
<p>use rowspan/colspan and a number in td or th to declare how long to span it</p>

django1app/templates/django1app/test.html
<html>
    <head>
       <title> this is the title of the site,should not be visible in browser</title>
    </head>

    <body>
        <h1>this is the title you will see in the browser</h1>
        <h2><b>bold lv 2 title</b> non bold <br />for comp.</h2>
        <hr />
    <p> <b> now this is bold, doesnt work in headers</b> test</p>
    <p> H<sub>2</sub><sup>3</sup></p>
    <p> <strong> use strong to for important text</strong></p>
    <p> <em> use em to put emphasis on sth</em></p>
    <blockquote cite="googl.com"><p> this is a blockquote</p></blockquote>
    <q><p> this uses q then p</p></q>
    <p> <q> this uses p then q</q></p>
    <p> <abbr title="Abbreation">abbr</abbr></p>
    <p> use <cite>cite</cite> to indicate a citation and <dfn>dfn</dfn> indicate a definition</p>
    <address>
        <p><a href="mailto:test@gmail.com">
            test@gmail.com</a></p>
        <p> 8574 am weg 3, tuzingen</p>
    </address>
    <p><ins>ins indicates somethin was insertet</ins> <del> del indicates somethin was deleted</del></p>
    <p><s> as indicates somethin is no longer accurate</s>  this is accurate</p>
    </body>
</html>

django1app/templates/django1app/topic.html
{% extends "django1app/base.html" %}

{% block content %}

    <p> Topic: {{topic }} </p>

    <p>Entries: </p>
    <p>
        <a href ="{% url 'django1app:new_entry' topic.id %}"> add a new entry </a>
    </p>
    <ul>
        {% for entry in entries %}
        <li>
            <p>{{entry.date_added|date:'M d,Y H:i' }}</p>
            <p> {{entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'django1app:edit_entry' entry.id %}">edit entry</a>
            </p>
        </li>
        {%empty%}
        <li>
            There are no entries for this topic.
        </li>
        {% endfor %}
    </ul>

{% endblock content%}

django1app/templates/django1app/topics.html
{% extends "django1app/base.html" %}

{% block content %}
<!-- ul is for unordered list -->
<p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li>
                <a href = "{%url 'django1app:topic' topic.id%}">{{topic}} </a>
            </li>
    <!-- the brackets indicate a template variable, li stands for list item, "/" indicates a closing of p,ul,li  -->
            {%empty%}
                <li> No topics have been added yet</li>
        {% endfor %}
    </ul>
<a href="{% url 'django1app:new_topic' %}">Add a new topic:</a>

{% endblock content %}

mealplanner/mymealplanner/templates/mymealplanner/index.html
<p> this is the landing page for my different mealplans</p>

users/templates/users/login.html
{% extends "django1app/base.html" %}

{%block content %}

{% if form.errors %}
<p>Your username and password dont match.Try again</p>
{% endif %}

<form method="post" action="{%url 'users:login' %}">
    {%csrf_token %}
    {{form.as_p}}

    <button name="submit">log in</button>
    <input type="hidden" name="next" value="{% url 'django1app:index' %}"/>
</form>

{%endblock content %}

users/templates/users/register.html
{% extends 'django1app/base.html' %}

{%block content %}

    <form method="post" action="{% url 'users:register' %}">
        {%csrf_token %}
        {{form.as_p }}

        <button name="submit">register</button>
        <input type = 'hidden' name = 'next' value="{%url 'django1app:index'%}"/>
        </form>

{% endblock content %}